components:
    schemas:
        CreateCustomerRequest:
            description: Запрос на создание клиента
            properties:
                email:
                    type: string
                name:
                    type: string
                phone:
                    type: string
            required:
                - id
                - email
                - customer
                - customers
                - customer_id
                - deal
            type: object
        CreateCustomerResponse:
            description: Ответ на создание клиента
            properties:
                customer:
                    $ref: '#/components/schemas/Customer'
            required:
                - email
                - customer
                - customers
                - customer_id
                - deal
                - id
            type: object
        CreateDealRequest:
            description: Запрос на создание сделки
            properties:
                amount:
                    format: double
                    type: number
                customer_id:
                    type: string
                title:
                    type: string
            required:
                - customers
                - customer_id
                - deal
                - id
                - email
                - customer
            type: object
        CreateDealResponse:
            description: Ответ на создание сделки
            properties:
                deal:
                    $ref: '#/components/schemas/Deal'
            required:
                - deal
                - id
                - email
                - customer
                - customers
                - customer_id
            type: object
        Customer:
            description: Модель клиента
            properties:
                email:
                    type: string
                id:
                    type: string
                name:
                    type: string
                phone:
                    type: string
            required:
                - customer
                - customers
                - customer_id
                - deal
                - id
                - email
            type: object
        Deal:
            description: Модель сделки
            properties:
                amount:
                    format: double
                    type: number
                customer_id:
                    type: string
                id:
                    type: string
                title:
                    type: string
            required:
                - email
                - customer
                - customers
                - customer_id
                - deal
                - id
            type: object
        ListCustomersResponse:
            description: Ответ со списком клиентов
            properties:
                customers:
                    items:
                        $ref: '#/components/schemas/Customer'
                    type: array
                next_page_token:
                    type: string
            required:
                - id
                - email
                - customer
                - customers
                - customer_id
                - deal
            type: object
        ListDealsResponse:
            description: Ответ со списком сделок
            properties:
                deals:
                    items:
                        $ref: '#/components/schemas/Deal'
                    type: array
            required:
                - deal
                - id
                - email
                - customer
                - customers
                - customer_id
            type: object
info:
    title: ""
    version: 0.0.1
openapi: 3.0.3
paths:
    /v1/customers:
        get:
            description: Получить список клиентов (с пагинацией)
            operationId: CustomerService_ListCustomers
            parameters:
                - in: query
                  name: page_size
                  schema:
                    format: int32
                    type: integer
                - in: query
                  name: page_token
                  schema:
                    type: string
            responses:
                "200":
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/ListCustomersResponse'
                    description: OK
            tags:
                - CustomerService
        post:
            description: Создать клиента
            operationId: CustomerService_CreateCustomer
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/CreateCustomerRequest'
                required: true
            responses:
                "200":
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/CreateCustomerResponse'
                    description: OK
            tags:
                - CustomerService
    /v1/customers/{customer_id}/deals:
        get:
            description: Получить список сделок клиента
            operationId: DealService_ListDeals
            parameters:
                - in: path
                  name: customer_id
                  required: true
                  schema:
                    type: string
            responses:
                "200":
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/ListDealsResponse'
                    description: OK
            tags:
                - DealService
    /v1/customers/{id}:
        get:
            description: Получить клиента по ID
            operationId: CustomerService_GetCustomer
            parameters:
                - in: path
                  name: id
                  required: true
                  schema:
                    type: string
            responses:
                "200":
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Customer'
                    description: OK
            tags:
                - CustomerService
    /v1/deals:
        post:
            description: Создать сделку
            operationId: DealService_CreateDeal
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/CreateDealRequest'
                required: true
            responses:
                "200":
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/CreateDealResponse'
                    description: OK
            tags:
                - DealService
tags:
    - description: Сервис для работы с клиентами
      name: CustomerService
    - description: Сервис для работы со сделками
      name: DealService
